### ISSUE TITLE
你好，请问可以添加对unity2018的支持吗？

### ISSUE THREAD

**Issue by qianmozhongheng** [Empty-ZZJ/HOILAI-Galgame-Framework#1]
我的版本号是2018.2.19f1（64bit）

新建一个3d项目文件后
导入资源包后出现错误
Assembly has reference to non-existent assembly 'GUID:2870bc0b4b018d04e8ebe52993b57c6d' (Assets/HGF/Tetra Attributes/Editor/TetraCreations.Attributes.Editor.asmdef)

即使切换成新建2d项目文件依然出现此类错误

**Comment by qianmozhongheng** [comment]
![批注 2024-01-01 001652](https://github.com/Empty-ZZJ/HOILAI-Galgame-Framework/assets/141086195/24151b8c-2468-4a3a-b463-d2f3f3d0342e)

**Comment by Empty-ZZJ** [comment]
好的，我们将会在1天之内完成对Unity2018的支持！

**Comment by Empty-ZZJ** [comment]
您好，我们经过排查发现是由于某些语法在Unity2018的C#版本上并不适用。我们将会在7个工作日内完成对框架的改写以支持更早版本的Unity。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月01日 00:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [Empty-ZZJ/HOILAI-Galgame-Framework] 你好，请问可以添加对unity2018的支持吗？ (Issue #1) |

2024-01-01.001652.jpg (view on web)

**Comment by Empty-ZZJ** [comment]
您好，我们已经与15点37分完成对Unity2018的支持，您可到该连接下载包体：https://github.com/Empty-ZZJ/HOILAI-Galgame-Framework/releases/tag/HGF_Unity2018

**Comment by qianmozhongheng** [comment]
实在是非常感谢！！爱你
