### ISSUE TITLE
2018版本的错误有点多....

### ISSUE THREAD

**Issue by qianmozhongheng** [Empty-ZZJ/HOILAI-Galgame-Framework#2]
首先开发人员辛苦了，可能是开发太累了，更改成c#4.0后，使用unity2018.2.19f1（64bit）导入发现GalManager_Text.CS这个脚本错误有点多，目前是我发现的错误：
1.第10行和第11行这个英文命名是否错误？default（不是defalut），speed（不是speend）
2.第84行的Alwayls是否是拼写错误 （应该是Always）
3.大量出现语法报错
这是我的编辑器报错日志文件：
[Editor.log](https://github.com/Empty-ZZJ/HOILAI-Galgame-Framework/files/13811811/Editor.log)
![2](https://github.com/Empty-ZZJ/HOILAI-Galgame-Framework/assets/141086195/678ca54d-58a6-4d86-96e1-6cb220e1756e)
![3](https://github.com/Empty-ZZJ/HOILAI-Galgame-Framework/assets/141086195/7e247ee5-91bb-4025-8207-20b5e5fccbf1)
![批注 2024-01-03 000225](https://github.com/Empty-ZZJ/HOILAI-Galgame-Framework/assets/141086195/7129343c-8a80-47d8-aecc-9246a184398b)

**Comment by qianmozhongheng** [comment]
这个是大大的版本运行产生的31个错误的日志文件
[Editor（31个错误）.log](https://github.com/Empty-ZZJ/HOILAI-Galgame-Framework/files/13811862/Editor.31.log)

**Comment by Empty-ZZJ** [comment]
您好，我们当前的开发设备上最早的Unity安装版本为Unity2018.4.13f1c1，这可能与您的Unity2018.2.19f1版本并不兼容。有关这个问题您可以直接联系到开发人员进行一步步调试直至达到您的预期目标。我们的联系方式如下，QQ：3563640373  。若您需要其他的联系方式可直接回复。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月03日 00:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Empty-ZZJ/HOILAI-Galgame-Framework] 2018版本的错误有点多.... (Issue #2) |

首先开发人员辛苦了，可能是开发太累了，更改成c#4.0后，使用unity2018.2.19f1（64bit）导入发现GalManager_Text.CS这个脚本错误有点多，目前是我发现的错误：
1.第10行和第11行这个英文命名是否错误？default（不是defalut），speed（不是speend）
2.第84行的Alwayls是否是拼写错误 （应该是Always）
3.大量出现语法报错
这是我的编辑器报错日志文件：
Editor.log
2.jpg (view on web)
3.jpg (view on web)
2024-01-03.000225.jpg (view on web)

**Comment by qianmozhongheng** [comment]
好的，谢谢
